# Site settings
title: Heoju's Blog
email: hoojh93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
url: "http://heojh93.github.io" # the subpath of your site, e.g. /blog/
baseurl: ""
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  heojh93

timezone: Asia/Seoul

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

category: [Home, Category, Tag]

paginate: 5
paginate_path: "/page:num/"

# About
author:
  name: "Juhwan Heo"

  photo: /public/images/profile_image.jpeg 
  about:
  social:
    facebook: WierdHeoju
    github: heojh93
    google: hoojh93
    steam:  76561198089795914

# Navigator
category_path: Category
tag_path: Tag


# disqus
disqus_shortname: wierdpants
